apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  containers:
    - name: minio
      image: quay.io/minio/minio:latest
      command:
        - /bin/bash
        - -c
      args:
        - minio server /data/minio --console-address :9090
      volumeMounts:
        - mountPath: /data/minio
          name: local-vol
      env:
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio_password
  nodeSelector:
    kubernetes.io/hostname: lima-rancher-desktop  # Assume Rancher Desktop (Mac or Windows) is running.
  volumes:
    - name: local-vol
      persistentVolumeClaim:
        claimName: minio-pvc
