apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-console
  namespace: minio
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-api
  namespace: minio
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
