version: '3.7'

networks:
  default:
    driver: bridge

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: on-failure
    volumes:
      - ~/data/minio:/data/minio
    ports:
      - '9000:9000'
      - '9090:9090'
    entrypoint: minio server /data/minio --console-address :9090
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    networks:
      - default
